apiVersion: v1
kind: Template
labels:
  app: rgwexporter
  template: rgwexporter-buildconfig-with-secret
metadata:
  annotations:
    description: RadosGW Exporter - BuildConfig with Secret
      see https://github.com/Worteks/docker-rgwexporter
    iconClass: icon-openshift
    openshift.io/display-name: RadosGW Exporter
    tags: rgwexporter
  name: rgwexporter-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-${FRONTNAME}-${RADOSGW_EXPORTER_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet RadosGW Exporter images
    labels:
      name: rgwexporter-${FRONTNAME}-${RADOSGW_EXPORTER_REPOSITORY_REF}
    name: rgwexporter-${FRONTNAME}-${RADOSGW_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${RADOSGW_EXPORTER_REPOSITORY_URL}
        ref: "${RADOSGW_EXPORTER_REPOSITORY_REF}"
      sourceSecret:
        name: git-${FRONTNAME}-${RADOSGW_EXPORTER_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: rgwexporter-${FRONTNAME}:${RADOSGW_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
- name: RADOSGW_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: RADOSGW_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your RadosGW Exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-rgwexporter.git
