apiVersion: v1
kind: Template
labels:
  app: rgwexporter
  template: rgwexporter-imagestream
metadata:
  annotations:
    description: RadosGW Exporter - ImageStream
      see https://github.com/Worteks/docker-rgwexporter
    iconClass: icon-openshift
    openshift.io/display-name: RadosGW Exporter
    tags: rgwexporter
  name: rgwexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet RadosGW Exporter image
    name: rgwexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
