apiVersion: v1
kind: Template
labels:
  app: radosgw
  template: radosgw-secret
metadata:
  annotations:
    description: RadosGW Exporter - Secret
      see https://github.com/Worteks/docker-rgwexporter
    iconClass: icon-openshift
    openshift.io/display-name: RadosGW Exporter
    tags: radosgw
  name: radosgw-secret
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: radosgw-${FRONTNAME}-conf
  data:
    ${CEPH_CLUSTER_NAME}.client.radosgw.keyring: |+
      [client.${RADOSGW_KEYRING_NAME}]
          key = ${RADOSGW_KEYRING_KEY}
          caps mon = "allow rwx"
          caps osd = "allow rwx"
    ${CEPH_CLUSTER_NAME}.conf: |+
      [global]
      fsid = ${CEPH_CLUSTER_ID}
      mon initial members = ${CEPH_INITIAL_MEMBERS}
      mon host = ${CEPH_MON_HOSTS}
      rgw admin entry = "admin"
      rgw enable apis = "s3, admin"
      rgw enable usage log = true
      rgw_frontends = "civetweb port=8080"
- kind: Secret
  apiVersion: v1
  metadata:
    annotations:
      template.openshift.io/expose-access-key: "{.data['s3-usage-access-key']}"
      template.openshift.io/expose-secret-key: "{.data['s3-usage-secret-key']}"
    name: radosgw-${FRONTNAME}
  stringData:
    s3-usage-access-key: ${RADOSGW_S3_USAGE_ACCESS_KEY}
    s3-usage-secret-key: ${RADOSGW_S3_USAGE_SECRET_KEY}
parameters:
- name: CEPH_CLUSTER_ID
  description: Ceph Cluster ID
  displayName: Ceph Cluster ID
  required: true
- name: CEPH_CLUSTER_NAME
  description: Ceph Cluster Name
  displayName: Ceph Cluster Name
  value: ceph
- name: CEPH_INITIAL_MEMBERS
  description: Comma-Separated list of Ceph Initial Cluster Members
  displayName: Ceph Initial Cluster Members
  required: true
- name: CEPH_MON_HOSTS
  description: Comma-Separated list of Ceph Monitor IP Addresses
  displayName: Ceph Monitor IP Addresses
  required: true
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: RADOSGW_KEYRING_KEY
  description: RadosGW Keyring Key
  displayName: RadosGW Keyring Key
  required: true
- name: RADOSGW_KEYRING_NAME
  description: RadosGW Keyring Name
  displayName: RadosGW Keyring Name
  required: true
